package coleccion.android

import coleccion.android.R.drawable
import java.util.Stack

class CardStack : Stack<Card>() {


    init {

        var cNums : Int = 0

    val bP1 = Card("Blue", 1, "Parallelogram", "Solid", drawable.colecci_n_blue_parallelogram_1)
    val bP2 = Card("Blue", 2, "Parallelogram", "Solid", drawable.colecci_n_blue_parallelogram_2)
    val bP3 = Card("Blue", 3, "Parallelogram", "Solid", drawable.colecci_n_blue_parallelogram_3)
    val bPE1 =
        Card("Blue", 1, "Parallelogram", "Empty", drawable.colecci_n_blue_parallelogram_e_1)
    val bPE2 =
        Card("Blue", 2, "Parallelogram", "Empty", drawable.colecci_n_blue_parallelogram_e_2)
    val bPE3 =
        Card("Blue", 3, "Parallelogram", "Empty", drawable.colecci_n_blue_parallelogram_e_3)
    val bPS1 = Card("Blue", 1, "Parallelogram", "Grid", drawable.colecci_n_blue_parallelogram_s_1)
    val bPS2 = Card("Blue", 2, "Parallelogram", "Grid", drawable.colecci_n_blue_parallelogram_s_2)
    val bPS3 = Card("Blue", 3, "Parallelogram", "Grid", drawable.colecci_n_blue_parallelogram_s_3)
    val gP1 = Card("Green", 1, "Parallelogram", "Solid", drawable.colecci_n_green_parallelogram_1)
    val gP2 = Card("Green", 2, "Parallelogram", "Solid", drawable.colecci_n_green_parallelogram_2)
    val gP3 = Card("Green", 3, "Parallelogram", "Solid", drawable.colecci_n_green_parallelogram_3)
    val gPE1 =
        Card("Green", 1, "Parallelogram", "Empty", drawable.colecci_n_green_parallelogram_e_1)
    val gPE2 =
        Card("Green", 2, "Parallelogram", "Empty", drawable.colecci_n_green_parallelogram_e_2)
    val gPE3 =
        Card("Green", 3, "Parallelogram", "Empty", drawable.colecci_n_green_parallelogram_e_3)
    val gPS1 =
        Card("Green", 1, "Parallelogram", "Grid", drawable.colecci_n_green_parallelogram_s_1)
    val gPS2 =
        Card("Green", 2, "Parallelogram", "Grid", drawable.colecci_n_green_parallelogram_s_2)
    val gPS3 =
        Card("Green", 3, "Parallelogram", "Grid", drawable.colecci_n_green_parallelogram_s_3)
    val oP1 =
        Card("Orange", 1, "Parallelogram", "Solid", drawable.colecci_n_orange_parallelogram_1)
    val oP2 =
        Card("Orange", 2, "Parallelogram", "Solid", drawable.colecci_n_orange_parallelogram_2)
    val oP3 =
        Card("Orange", 3, "Parallelogram", "Solid", drawable.colecci_n_orange_parallelogram_3)
    val oPE1 =
        Card("Orange", 1, "Parallelogram", "Empty", drawable.colecci_n_orange_parallelogram_e_1)
    val oPE2 =
        Card("Orange", 2, "Parallelogram", "Empty", drawable.colecci_n_orange_parallelogram_e_2)
    val oPE3 =
        Card("Orange", 3, "Parallelogram", "Empty", drawable.colecci_n_orange_parallelogram_e_3)
    val oPS1 =
        Card("Orange", 1, "Parallelogram", "Grid", drawable.colecci_n_orange_parallelogram_s_1)
    val oPS2 =
        Card("Orange", 2, "Parallelogram", "Grid", drawable.colecci_n_orange_parallelogram_s_2)
    val oPS3 =
        Card("Orange", 3, "Parallelogram", "Grid", drawable.colecci_n_orange_parallelogram_s_3)
    val rP1 = Card("Red", 1, "Parallelogram", "Solid", drawable.colecci_n_red_parallelogram_1)
    val rP2 = Card("Red", 2, "Parallelogram", "Solid", drawable.colecci_n_red_parallelogram_2)
    val rP3 = Card("Red", 3, "Parallelogram", "Solid", drawable.colecci_n_red_parallelogram_3)
    val rPE1 = Card("Red", 1, "Parallelogram", "Empty", drawable.colecci_n_red_parallelogram_e_1)
    val rPE2 = Card("Red", 2, "Parallelogram", "Empty", drawable.colecci_n_red_parallelogram_e_2)
    val rPE3 = Card("Red", 3, "Parallelogram", "Empty", drawable.colecci_n_red_parallelogram_e_3)
    val rPS1 = Card("Red", 1, "Parallelogram", "Grid", drawable.colecci_n_red_parallelogram_s_1)
    val rPS2 = Card("Red", 2, "Parallelogram", "Grid", drawable.colecci_n_red_parallelogram_s_2)
    val rPS3 = Card("Red", 3, "Parallelogram", "Grid", drawable.colecci_n_red_parallelogram_s_3)
    val bR1 = Card("Blue", 1, "Rectangle", "Solid", drawable.colecci_n_blue_rectangle_1)
    val bR2 = Card("Blue", 2, "Rectangle", "Solid", drawable.colecci_n_blue_rectangle_2)
    val bR3 = Card("Blue", 3, "Rectangle", "Solid", drawable.colecci_n_blue_rectangle_3)
    val bRE1 = Card("Blue", 1, "Rectangle", "Empty", drawable.colecci_n_blue_rectangle_e_1)
    val bRE2 = Card("Blue", 2, "Rectangle", "Empty", drawable.colecci_n_blue_rectangle_e_2)
    val bRE3 = Card("Blue", 3, "Rectangle", "Empty", drawable.colecci_n_blue_rectangle_e_3)
    val bRS1 = Card("Blue", 1, "Rectangle", "Grid", drawable.colecci_n_blue_rectangle_s_1)
    val bRS2 = Card("Blue", 2, "Rectangle", "Grid", drawable.colecci_n_blue_rectangle_s_2)
    val bRS3 = Card("Blue", 3, "Rectangle", "Grid", drawable.colecci_n_blue_rectangle_s_3)
    val gR1 = Card("Green", 1, "Rectangle", "Solid", drawable.colecci_n_green_rectangle_1)
    val gR2 = Card("Green", 2, "Rectangle", "Solid", drawable.colecci_n_green_rectangle_2)
    val gR3 = Card("Green", 3, "Rectangle", "Solid", drawable.colecci_n_green_rectangle_3)
    val gRE1 = Card("Green", 1, "Rectangle", "Empty", drawable.colecci_n_green_rectangle_e_1)
    val gRE2 = Card("Green", 2, "Rectangle", "Empty", drawable.colecci_n_green_rectangle_e_2)
    val gRE3 = Card("Green", 3, "Rectangle", "Empty", drawable.colecci_n_green_rectangle_e_3)
    val gRS1 = Card("Green", 1, "Rectangle", "Grid", drawable.colecci_n_green_rectangle_s_1)
    val gRS2 = Card("Green", 2, "Rectangle", "Grid", drawable.colecci_n_green_rectangle_s_2)
    val gRS3 = Card("Green", 3, "Rectangle", "Grid", drawable.colecci_n_green_rectangle_s_3)
    val oR1 = Card("Orange", 1, "Rectangle", "Solid", drawable.colecci_n_orange_rectangle_1)
    val oR2 = Card("Orange", 2, "Rectangle", "Solid", drawable.colecci_n_orange_rectangle_2)
    val oR3 = Card("Orange", 3, "Rectangle", "Solid", drawable.colecci_n_orange_rectangle_3)
    val oRE1 = Card("Orange", 1, "Rectangle", "Empty", drawable.colecci_n_orange_rectangle_e_1)
    val oRE2 = Card("Orange", 2, "Rectangle", "Empty", drawable.colecci_n_orange_rectangle_e_2)
    val oRE3 = Card("Orange", 3, "Rectangle", "Empty", drawable.colecci_n_orange_rectangle_e_3)
    val oRS1 = Card("Orange", 1, "Rectangle", "Grid", drawable.colecci_n_orange_rectangle_s_1)
    val oRS2 = Card("Orange", 2, "Rectangle", "Grid", drawable.colecci_n_orange_rectangle_s_2)
    val oRS3 = Card("Orange", 3, "Rectangle", "Grid", drawable.colecci_n_orange_rectangle_s_3)
    val rR1 = Card("Red", 1, "Rectangle", "Solid", drawable.colecci_n_red_rectangle_1)
    val rR2 = Card("Red", 2, "Rectangle", "Solid", drawable.colecci_n_red_rectangle_2)
    val rR3 = Card("Red", 3, "Rectangle", "Solid", drawable.colecci_n_red_rectangle_3)
    val rRE1 = Card("Red", 1, "Rectangle", "Empty", drawable.colecci_n_red_rectangle_e_1)
    val rRE2 = Card("Red", 2, "Rectangle", "Empty", drawable.colecci_n_red_rectangle_e_2)
    val rRE3 = Card("Red", 3, "Rectangle", "Empty", drawable.colecci_n_red_rectangle_e_3)
    val rRS1 = Card("Red", 1, "Rectangle", "Grid", drawable.colecci_n_red_rectangle_s_1)
    val rRS2 = Card("Red", 2, "Rectangle", "Grid", drawable.colecci_n_red_rectangle_s_2)
    val rRS3 = Card("Red", 3, "Rectangle", "Grid", drawable.colecci_n_red_rectangle_s_3)
    val bS1 = Card("Blue", 1, "Semicircle", "Solid", drawable.colecci_n_blue_semicircle_1)
    val bS2 = Card("Blue", 2, "Semicircle", "Solid", drawable.colecci_n_blue_semicircle_2)
    val bS3 = Card("Blue", 3, "Semicircle", "Solid", drawable.colecci_n_blue_semicircle_3)
    val bSE1 = Card("Blue", 1, "Semicircle", "Empty", drawable.colecci_n_blue_semicircle_e_1)
    val bSE2 = Card("Blue", 2, "Semicircle", "Empty", drawable.colecci_n_blue_semicircle_e_2)
    val bSE3 = Card("Blue", 3, "Semicircle", "Empty", drawable.colecci_n_blue_semicircle_e_3)
    val bSS1 = Card("Blue", 1, "Semicircle", "Grid", drawable.colecci_n_blue_semicircle_s_1)
    val bSS2 = Card("Blue", 2, "Semicircle", "Grid", drawable.colecci_n_blue_semicircle_s_2)
    val bSS3 = Card("Blue", 3, "Semicircle", "Grid", drawable.colecci_n_blue_semicircle_s_3)
    val gS1 = Card("Green", 1, "Semicircle", "Solid", drawable.colecci_n_green_semicircle_1)
    val gS2 = Card("Green", 2, "Semicircle", "Solid", drawable.colecci_n_green_semicircle_2)
    val gS3 = Card("Green", 3, "Semicircle", "Solid", drawable.colecci_n_green_semicircle_3)
    val gSE1 = Card("Green", 1, "Semicircle", "Empty", drawable.colecci_n_green_semicircle_e_1)
    val gSE2 = Card("Green", 2, "Semicircle", "Empty", drawable.colecci_n_green_semicircle_e_2)
    val gSE3 = Card("Green", 3, "Semicircle", "Empty", drawable.colecci_n_green_semicircle_e_3)
    val gSS1 = Card("Green", 1, "Semicircle", "Grid", drawable.colecci_n_green_semicircle_s_1)
    val gSS2 = Card("Green", 2, "Semicircle", "Grid", drawable.colecci_n_green_semicircle_s_2)
    val gSS3 = Card("Green", 3, "Semicircle", "Grid", drawable.colecci_n_green_semicircle_s_3)
    val oS1 = Card("Orange", 1, "Semicircle", "Solid", drawable.colecci_n_orange_semicircle_1)
    val oS2 = Card("Orange", 2, "Semicircle", "Solid", drawable.colecci_n_orange_semicircle_2)
    val oS3 = Card("Orange", 3, "Semicircle", "Solid", drawable.colecci_n_orange_semicircle_3)
    val oSE1 = Card("Orange", 1, "Semicircle", "Empty", drawable.colecci_n_orange_semicircle_e_1)
    val oSE2 = Card("Orange", 2, "Semicircle", "Empty", drawable.colecci_n_orange_semicircle_e_2)
    val oSE3 = Card("Orange", 3, "Semicircle", "Empty", drawable.colecci_n_orange_semicircle_e_3)
    val oSS1 = Card("Orange", 1, "Semicircle", "Grid", drawable.colecci_n_orange_semicircle_s_1)
    val oSS2 = Card("Orange", 2, "Semicircle", "Grid", drawable.colecci_n_orange_semicircle_s_2)
    val oSS3 = Card("Orange", 3, "Semicircle", "Grid", drawable.colecci_n_orange_semicircle_s_3)
    val rS1 = Card("Red", 1, "Semicircle", "Solid", drawable.colecci_n_red_semicircle_1)
    val rS2 = Card("Red", 2, "Semicircle", "Solid", drawable.colecci_n_red_semicircle_2)
    val rS3 = Card("Red", 3, "Semicircle", "Solid", drawable.colecci_n_red_semicircle_3)
    val rSE1 = Card("Red", 1, "Semicircle", "Empty", drawable.colecci_n_red_semicircle_e_1)
    val rSE2 = Card("Red", 2, "Semicircle", "Empty", drawable.colecci_n_red_semicircle_e_2)
    val rSE3 = Card("Red", 3, "Semicircle", "Empty", drawable.colecci_n_red_semicircle_e_3)
    val rSS1 = Card("Red", 1, "Semicircle", "Grid", drawable.colecci_n_red_semicircle_s_1)
    val rSS2 = Card("Red", 2, "Semicircle", "Grid", drawable.colecci_n_red_semicircle_s_2)
    val rSS3 = Card("Red", 3, "Semicircle", "Grid", drawable.colecci_n_red_semicircle_s_3)
    val bT1 = Card("Blue", 1, "Triangle", "Solid", drawable.colecci_n_blue_triangle_1)
    val bT2 = Card("Blue", 2, "Triangle", "Solid", drawable.colecci_n_blue_triangle_2)
    val bT3 = Card("Blue", 3, "Triangle", "Solid", drawable.colecci_n_blue_triangle_3)
    val bTE1 = Card("Blue", 1, "Triangle", "Empty", drawable.colecci_n_blue_triangle_e_1)
    val bTE2 = Card("Blue", 2, "Triangle", "Empty", drawable.colecci_n_blue_triangle_e_2)
    val bTE3 = Card("Blue", 3, "Triangle", "Empty", drawable.colecci_n_blue_triangle_e_3)
    val bTS1 = Card("Blue", 1, "Triangle", "Grid", drawable.colecci_n_blue_triangle_s_1)
    val bTS2 = Card("Blue", 2, "Triangle", "Grid", drawable.colecci_n_blue_triangle_s_2)
    val bTS3 = Card("Blue", 3, "Triangle", "Grid", drawable.colecci_n_blue_triangle_s_3)
    val gT1 = Card("Green", 1, "Triangle", "Solid", drawable.colecci_n_green_triangle_1)
    val gT2 = Card("Green", 2, "Triangle", "Solid", drawable.colecci_n_green_triangle_2)
    val gT3 = Card("Green", 3, "Triangle", "Solid", drawable.colecci_n_green_triangle_3)
    val gTE1 = Card("Green", 1, "Triangle", "Empty", drawable.colecci_n_green_triangle_e_1)
    val gTE2 = Card("Green", 2, "Triangle", "Empty", drawable.colecci_n_green_triangle_e_2)
    val gTE3 = Card("Green", 3, "Triangle", "Empty", drawable.colecci_n_green_triangle_e_3)
    val gTS1 = Card("Green", 1, "Triangle", "Grid", drawable.colecci_n_green_triangle_s_1)
    val gTS2 = Card("Green", 2, "Triangle", "Grid", drawable.colecci_n_green_triangle_s_2)
    val gTS3 = Card("Green", 3, "Triangle", "Grid", drawable.colecci_n_green_triangle_s_3)
    val oT1 = Card("Orange", 1, "Triangle", "Solid", drawable.colecci_n_orange_triangle_1)
    val oT2 = Card("Orange", 2, "Triangle", "Solid", drawable.colecci_n_orange_triangle_2)
    val oT3 = Card("Orange", 3, "Triangle", "Solid", drawable.colecci_n_orange_triangle_3)
    val oTE1 = Card("Orange", 1, "Triangle", "Empty", drawable.colecci_n_orange_triangle_e_1)
    val oTE2 = Card("Orange", 2, "Triangle", "Empty", drawable.colecci_n_orange_triangle_e_2)
    val oTE3 = Card("Orange", 3, "Triangle", "Empty", drawable.colecci_n_orange_triangle_e_3)
    val oTS1 = Card("Orange", 1, "Triangle", "Grid", drawable.colecci_n_orange_triangle_s_1)
    val oTS2 = Card("Orange", 2, "Triangle", "Grid", drawable.colecci_n_orange_triangle_s_2)
    val oTS3 = Card("Orange", 3, "Triangle", "Grid", drawable.colecci_n_orange_triangle_s_3)
    val rT1 = Card("Red", 1, "Triangle", "Solid", drawable.colecci_n_red_triangle_1)
    val rT2 = Card("Red", 2, "Triangle", "Solid", drawable.colecci_n_red_triangle_2)
    val rT3 = Card("Red", 3, "Triangle", "Solid", drawable.colecci_n_red_triangle_3)
    val rTE1 = Card("Red", 1, "Triangle", "Empty", drawable.colecci_n_red_triangle_e_1)
    val rTE2 = Card("Red", 2, "Triangle", "Empty", drawable.colecci_n_red_triangle_e_2)
    val rTE3 = Card("Red", 3, "Triangle", "Empty", drawable.colecci_n_red_triangle_e_3)
    val rTS1 = Card("Red", 1, "Triangle", "Grid", drawable.colecci_n_red_triangle_s_1)
    val rTS2 = Card("Red", 2, "Triangle", "Grid", drawable.colecci_n_red_triangle_s_2)
    val rTS3 = Card("Red", 3, "Triangle", "Grid", drawable.colecci_n_red_triangle_s_3)

        this.push(	bP1	)
        this.push(	bP2	)
        this.push(	bP3	)
        this.push(	bPE1	)
        this.push(	bPE2	)
        this.push(	bPE3	)
        this.push(	bPS1	)
        this.push(	bPS2	)
        this.push(	bPS3	)
        this.push(	gP1	)
        this.push(	gP2	)
        this.push(	gP3	)
        this.push(	gPE1	)
        this.push(	gPE2	)
        this.push(	gPE3	)
        this.push(	gPS1	)
        this.push(	gPS2	)
        this.push(	gPS3	)
        this.push(	oP1	)
        this.push(	oP2	)
        this.push(	oP3	)
        this.push(	oPE1	)
        this.push(	oPE2	)
        this.push(	oPE3	)
        this.push(	oPS1	)
        this.push(	oPS2	)
        this.push(	oPS3	)
        this.push(	rP1	)
        this.push(	rP2	)
        this.push(	rP3	)
        this.push(	rPE1	)
        this.push(	rPE2	)
        this.push(	rPE3	)
        this.push(	rPS1	)
        this.push(	rPS2	)
        this.push(	rPS3	)
        this.push(	bR1	)
        this.push(	bR2	)
        this.push(	bR3	)
        this.push(	bRE1	)
        this.push(	bRE2	)
        this.push(	bRE3	)
        this.push(	bRS1	)
        this.push(	bRS2	)
        this.push(	bRS3	)
        this.push(	gR1	)
        this.push(	gR2	)
        this.push(	gR3	)
        this.push(	gRE1	)
        this.push(	gRE2	)
        this.push(	gRE3	)
        this.push(	gRS1	)
        this.push(	gRS2	)
        this.push(	gRS3	)
        this.push(	oR1	)
        this.push(	oR2	)
        this.push(	oR3	)
        this.push(	oRE1	)
        this.push(	oRE2	)
        this.push(	oRE3	)
        this.push(	oRS1	)
        this.push(	oRS2	)
        this.push(	oRS3	)
        this.push(	rR1	)
        this.push(	rR2	)
        this.push(	rR3	)
        this.push(	rRE1	)
        this.push(	rRE2	)
        this.push(	rRE3	)
        this.push(	rRS1	)
        this.push(	rRS2	)
        this.push(	rRS3	)
        this.push(	bS1	)
        this.push(	bS2	)
        this.push(	bS3	)
        this.push(	bSE1	)
        this.push(	bSE2	)
        this.push(	bSE3	)
        this.push(	bSS1	)
        this.push(	bSS2	)
        this.push(	bSS3	)
        this.push(	gS1	)
        this.push(	gS2	)
        this.push(	gS3	)
        this.push(	gSE1	)
        this.push(	gSE2	)
        this.push(	gSE3	)
        this.push(	gSS1	)
        this.push(	gSS2	)
        this.push(	gSS3	)
        this.push(	oS1	)
        this.push(	oS2	)
        this.push(	oS3	)
        this.push(	oSE1	)
        this.push(	oSE2	)
        this.push(	oSE3	)
        this.push(	oSS1	)
        this.push(	oSS2	)
        this.push(	oSS3	)
        this.push(	rS1	)
        this.push(	rS2	)
        this.push(	rS3	)
        this.push(	rSE1	)
        this.push(	rSE2	)
        this.push(	rSE3	)
        this.push(	rSS1	)
        this.push(	rSS2	)
        this.push(	rSS3	)
        this.push(	bT1	)
        this.push(	bT2	)
        this.push(	bT3	)
        this.push(	bTE1	)
        this.push(	bTE2	)
        this.push(	bTE3	)
        this.push(	bTS1	)
        this.push(	bTS2	)
        this.push(	bTS3	)
        this.push(	gT1	)
        this.push(	gT2	)
        this.push(	gT3	)
        this.push(	gTE1	)
        this.push(	gTE2	)
        this.push(	gTE3	)
        this.push(	gTS1	)
        this.push(	gTS2	)
        this.push(	gTS3	)
        this.push(	oT1	)
        this.push(	oT2	)
        this.push(	oT3	)
        this.push(	oTE1	)
        this.push(	oTE2	)
        this.push(	oTE3	)
        this.push(	oTS1	)
        this.push(	oTS2	)
        this.push(	oTS3	)
        this.push(	rT1	)
        this.push(	rT2	)
        this.push(	rT3	)
        this.push(	rTE1	)
        this.push(	rTE2	)
        this.push(	rTE3	)
        this.push(	rTS1	)
        this.push(	rTS2	)
        this.push(	rTS3	)

        this.shuffle()
    }
}

fun getCard(): Card {
    val deck = CardStack()
    var card = deck.peek()
    deck.pop()

    return card
}



